coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
    patch:
      default:
        target: 90%
        threshold: 0%

ignore:
  - "build/**/*"
  - "coverage/**/*"
  - "js/**/*"
  - "tests/**/*"
  - "vendor/**/*"
  - "src/main.ts"
  - "src/files/actions.ts"
  - "src/files/new-menu.ts"
  - "src/sw/**/*"
  - "src/types/**/*"
  - "src/view/**/*"
  - "src/viewer/**/*"
